"""
RLT-Style Reward Function for Hint Generation (with Student Perplexity KL Proxy)

This reward function computes how well a hint helps a frozen student model
understand the correct solution. The reward is based on:

1. r_SS: Log-probability of solution given question and hint
2. r_KL_proxy: Student perplexity on hint (proxy for KL divergence)

Final Reward = r_SS - λ * r_KL_proxy

This version uses student perplexity as a proxy for KL divergence,
avoiding the need to load the teacher model during reward computation.
"""

import torch
import numpy as np
from typing import Optional, Any
from transformers import AutoModelForCausalLM, AutoTokenizer
from threading import Lock

# Global student model (loaded once and reused)
_student_model = None
_student_tokenizer = None
_student_lock = Lock()
_device = None

# Counter for logging (to avoid printing every single sample)
_log_counter = 0
_LOG_EVERY_N = 10  # Print debug info every N samples


def _print_separator(title: str = ""):
    """Print a visual separator for debug output."""
    print("\n" + "=" * 80)
    if title:
        print(f"  {title}")
        print("=" * 80)


def _truncate_for_display(text: str, max_len: int = 500) -> str:
    """Truncate text for display purposes."""
    if len(text) <= max_len:
        return text
    return text[:max_len] + f"\n... [truncated, total {len(text)} chars]"


def _get_available_device(preferred_device: str = "auto") -> str:
    """
    Get the best available device for the student model.
    Ray workers may not have GPU access, so we need to handle this gracefully.

    Args:
        preferred_device: "auto", "cpu", "cuda:0", "cuda:1", etc.
    """
    # Check if CUDA is available at all
    if not torch.cuda.is_available():
        print(f"[WARNING] CUDA not available in this process, using CPU")
        return "cpu"

    # Get the number of visible GPUs
    num_gpus = torch.cuda.device_count()
    print(f"[INFO] Process has access to {num_gpus} GPU(s)")

    if num_gpus == 0:
        print(f"[WARNING] No GPUs visible to this process, using CPU")
        return "cpu"

    # Handle "auto" - use first available GPU
    if preferred_device == "auto":
        return "cuda:0"

    # Handle "cpu" explicitly
    if preferred_device == "cpu":
        return "cpu"

    # Parse the preferred device (e.g., "cuda:1")
    if preferred_device.startswith("cuda:"):
        try:
            gpu_idx = int(preferred_device.split(":")[1])
            if gpu_idx < num_gpus:
                return preferred_device
            else:
                # Fall back to last available GPU
                fallback = f"cuda:{num_gpus - 1}"
                print(f"[WARNING] {preferred_device} not available, using {fallback}")
                return fallback
        except ValueError:
            pass

    # Default to first available GPU
    return "cuda:0"


def _load_student_model(
    model_name: str = "Qwen/Qwen2.5-Coder-3B-Instruct",
    device: str = "cuda:1",  # Use second GPU for student
) -> tuple:
    """Load the frozen student model for reward computation."""
    global _student_model, _student_tokenizer, _device

    with _student_lock:
        if _student_model is None:
            # Auto-detect best available device
            actual_device = _get_available_device(device)
            print(f"Loading student model: {model_name} on {actual_device} (requested: {device})")

            _student_tokenizer = AutoTokenizer.from_pretrained(
                model_name,
                trust_remote_code=True,
                padding_side="left"
            )
            if _student_tokenizer.pad_token is None:
                _student_tokenizer.pad_token = _student_tokenizer.eos_token

            # Use appropriate dtype based on device
            if actual_device == "cpu":
                dtype = torch.float32  # CPU doesn't support bfloat16 well
            else:
                dtype = torch.bfloat16

            _student_model = AutoModelForCausalLM.from_pretrained(
                model_name,
                torch_dtype=dtype,
                trust_remote_code=True,
                device_map=actual_device,
            )
            _student_model.eval()
            _device = actual_device
            print(f"Student model loaded successfully on {actual_device}")

    return _student_model, _student_tokenizer


def compute_solution_logprob(
    question: str,
    hint: str,
    solution: str,
    student_model: Any,
    student_tokenizer: Any,
    max_length: int = 2048,
    verbose: bool = False,
) -> dict:
    """
    Compute the log-probability of the solution given question and hint.

    This is the r_SS component of the RLT reward.

    Args:
        question: The coding problem
        hint: The hint generated by the teacher
        solution: The correct solution code
        student_model: The frozen student model
        student_tokenizer: The student model's tokenizer
        max_length: Maximum sequence length
        verbose: Whether to print debug information

    Returns:
        dict with 'mean_logprob', 'min_logprob', 'total_logprob', 'num_tokens'
    """
    # Build the prompt for the student using HTML-style tags
    # Format: question with hint -> solution
    messages = [
        {
            "role": "user",
            "content": f"""Solve the following problem using the provided hint.

<question>
{question}
</question>

<hint>
{hint}
</hint>

<answer>"""
        },
        {
            "role": "assistant",
            "content": solution + "\n</answer>"
        }
    ]

    # Tokenize the full conversation
    full_text = student_tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=False
    )

    # Tokenize prompt (without solution) to find where solution starts
    prompt_messages = [
        {
            "role": "user",
            "content": f"""Solve the following problem using the provided hint.

<question>
{question}
</question>

<hint>
{hint}
</hint>

<answer>"""
        }
    ]
    prompt_text = student_tokenizer.apply_chat_template(
        prompt_messages,
        tokenize=False,
        add_generation_prompt=True
    )

    # Debug: Print student model input
    if verbose:
        _print_separator("STUDENT MODEL INPUT (r_SS)")
        print(f"[Full text sent to student model]:\n{_truncate_for_display(full_text, 1000)}")
        print(f"\n[Prompt length]: {len(prompt_text)} chars")
        print(f"[Solution length]: {len(solution)} chars")

    # Tokenize
    full_encoding = student_tokenizer(
        full_text,
        return_tensors="pt",
        truncation=True,
        max_length=max_length,
        add_special_tokens=False
    )

    prompt_encoding = student_tokenizer(
        prompt_text,
        return_tensors="pt",
        truncation=True,
        max_length=max_length,
        add_special_tokens=False
    )

    input_ids = full_encoding["input_ids"].to(student_model.device)
    prompt_len = prompt_encoding["input_ids"].shape[1]

    # Get logits from student model
    with torch.no_grad():
        outputs = student_model(input_ids=input_ids)
        logits = outputs.logits

    # Compute log probabilities for solution tokens only
    # logits shape: (1, seq_len, vocab_size)
    # We want P(token_i | token_0, ..., token_{i-1})

    # Shift logits and labels for next-token prediction
    shift_logits = logits[:, prompt_len-1:-1, :]  # Logits that predict solution tokens
    shift_labels = input_ids[:, prompt_len:]  # Solution tokens

    if shift_labels.shape[1] == 0:
        # No solution tokens to score
        return {
            "mean_logprob": -10.0,
            "min_logprob": -10.0,
            "total_logprob": -10.0,
            "num_tokens": 0
        }

    # Compute log softmax
    log_probs = torch.log_softmax(shift_logits, dim=-1)

    # Gather log probs for the actual tokens
    token_log_probs = torch.gather(
        log_probs,
        dim=-1,
        index=shift_labels.unsqueeze(-1)
    ).squeeze(-1)

    # Compute statistics
    mean_logprob = token_log_probs.mean().item()
    min_logprob = token_log_probs.min().item()
    total_logprob = token_log_probs.sum().item()
    num_tokens = token_log_probs.shape[1]

    return {
        "mean_logprob": mean_logprob,
        "min_logprob": min_logprob,
        "total_logprob": total_logprob,
        "num_tokens": num_tokens
    }


def compute_student_perplexity(
    question: str,
    hint: str,
    student_model: Any,
    student_tokenizer: Any,
    max_length: int = 2048,
    verbose: bool = False
) -> dict:
    """
    Compute student's perplexity on the hint given only the question.
    
    This serves as a proxy for KL divergence without needing the teacher model.
    
    High perplexity = hint is unnatural/surprising to student
                    = teacher is using info student doesn't have
                    = similar to high KL divergence
    
    Low perplexity = hint is natural/expected by student
                   = hint could have been generated without solution
                   = similar to low KL divergence
    
    Intuition:
    - If the student (who doesn't see the solution) finds the hint very
      surprising (high perplexity), it means the hint probably requires
      knowledge of the solution to make sense.
    - If the student finds the hint natural (low perplexity), it means
      the hint is a reasonable thing to say given just the question.
    
    Args:
        question: The coding problem
        hint: The hint generated by the teacher
        student_model: The frozen student model
        student_tokenizer: Student tokenizer
        max_length: Maximum sequence length
        verbose: Whether to print debug info
    
    Returns:
        dict with 'perplexity', 'mean_logprob', 'min_logprob', 'num_tokens'
    """
    # Student sees: question -> hint (NO solution)
    messages = [
        {
            "role": "user",
            "content": f"""Generate a helpful hint for solving this problem.

<question>
{question}
</question>

<hint>"""
        },
        {
            "role": "assistant",
            "content": hint
        }
    ]
    
    full_text = student_tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=False
    )
    
    # Get prompt length (everything before hint)
    prompt_messages = [
        {
            "role": "user",
            "content": f"""Generate a helpful hint for solving this problem.

<question>
{question}
</question>

<hint>"""
        }
    ]
    prompt_text = student_tokenizer.apply_chat_template(
        prompt_messages,
        tokenize=False,
        add_generation_prompt=True
    )
    
    if verbose:
        _print_separator("STUDENT PERPLEXITY (KL Proxy)")
        print(f"[Context]: Student sees question only (NO solution)")
        print(f"[Task]: How surprising is this hint to the student?")
        print(f"\n[Prompt]:\n{_truncate_for_display(prompt_text, 500)}")
        print(f"\n[Hint to evaluate]:\n{_truncate_for_display(hint, 500)}")
    
    # Tokenize
    full_encoding = student_tokenizer(
        full_text,
        return_tensors="pt",
        truncation=True,
        max_length=max_length,
        add_special_tokens=False
    )
    
    prompt_encoding = student_tokenizer(
        prompt_text,
        return_tensors="pt",
        truncation=True,
        max_length=max_length,
        add_special_tokens=False
    )
    
    input_ids = full_encoding["input_ids"].to(student_model.device)
    prompt_len = prompt_encoding["input_ids"].shape[1]
    
    # Get logits from student model
    with torch.no_grad():
        outputs = student_model(input_ids=input_ids)
        logits = outputs.logits
    
    # Compute log probs for hint tokens
    shift_logits = logits[:, prompt_len-1:-1, :]
    shift_labels = input_ids[:, prompt_len:]
    
    if shift_labels.shape[1] == 0:
        return {
            "perplexity": 1.0,
            "mean_logprob": 0.0,
            "min_logprob": 0.0,
            "num_tokens": 0
        }
    
    log_probs = torch.log_softmax(shift_logits, dim=-1)
    token_log_probs = torch.gather(
        log_probs,
        dim=-1,
        index=shift_labels.unsqueeze(-1)
    ).squeeze(-1)
    
    # Compute statistics
    mean_log_prob = token_log_probs.mean().item()
    min_log_prob = token_log_probs.min().item()
    num_tokens = token_log_probs.shape[1]
    
    # Perplexity = exp(-mean(log_prob))
    # Lower is better (more natural hint)
    perplexity = np.exp(-mean_log_prob)
    
    if verbose:
        print(f"\n[Student Perplexity Statistics]:")
        print(f"  - mean_log_prob: {mean_log_prob:.4f}")
        print(f"  - min_log_prob:  {min_log_prob:.4f}")
        print(f"  - perplexity:    {perplexity:.4f}")
        print(f"  - num_tokens:    {num_tokens}")
        print(f"\n[Interpretation]:")
        if perplexity < 10:
            print(f"  ✓ Low perplexity - hint is natural for student")
        elif perplexity < 50:
            print(f"  ~ Medium perplexity - hint is somewhat surprising")
        else:
            print(f"  ✗ High perplexity - hint requires solution knowledge")
    
    return {
        "perplexity": perplexity,
        "mean_logprob": mean_log_prob,
        "min_logprob": min_log_prob,
        "num_tokens": num_tokens
    }


def extract_hint_from_response(response: str) -> str:
    """
    Extract the hint from the teacher's response.
    The teacher generates content after <hint> tag, may or may not close with </hint>.
    """
    hint = response.strip()

    # The prompt ends with <hint>, so the response is the hint content
    # Check if there's a closing </hint> tag
    if "</hint>" in hint.lower():
        end = hint.lower().find("</hint>")
        hint = hint[:end].strip()

    return hint


def compute_score(
    data_source: str,
    solution_str: str,
    ground_truth: Any,
    extra_info: Optional[dict] = None,
    # Reward function kwargs
    student_model_name: str = "Qwen/Qwen2.5-Coder-3B",
    student_device: str = "cuda:1",
    alpha: float = 0.01,  # Weight for min/max terms (RLT paper uses 0.01)
    lambda_kl: float = 3.0,  # Weight for KL term (RLT paper uses 3.0)
    use_kl_proxy: bool = True,  # Whether to use student perplexity as KL proxy
    perplexity_scale: float = 1.0,  # Scaling factor for perplexity -> penalty conversion
    length_penalty_threshold: int = 10,  # Minimum hint length
    max_hint_length: int = 512,  # Maximum hint length in chars
    solution_copy_penalty: float = -10.0,  # Penalty for copying solution
    empty_hint_penalty: float = -10.0,  # Penalty for empty hints
    log_every_n: int = 10,  # Print debug info every N samples
) -> float:
    """
    Compute the RLT-style reward for a generated hint using student perplexity as KL proxy.

    This function is called by verl's reward manager for each generated response.
    
    The full RLT reward formula is:
        r_RLT = r_SS - λ * r_KL_proxy
    
    where:
        r_SS = mean(log P(solution | question, hint)) + α * min(log P(...))
        r_KL_proxy = log(perplexity(hint | question)) + α * min(log P(hint | question))
    
    The perplexity proxy captures the same intuition as KL divergence:
    - High perplexity = hint is surprising to student = needs solution knowledge
    - Low perplexity = hint is natural to student = generalizable reasoning

    Args:
        data_source: Identifier for the data source
        solution_str: The teacher's generated response (containing the hint)
        ground_truth: Dict containing 'question' and 'solution'
        extra_info: Additional info dict with 'question' and 'solution'
        student_model_name: Name of the frozen student model
        student_device: Device to run student model on
        alpha: Weight for the min/max terms in reward (default: 0.01)
        lambda_kl: Weight for KL proxy term (default: 3.0)
        use_kl_proxy: Whether to include perplexity-based KL proxy (default: True)
        perplexity_scale: Scaling for perplexity conversion (default: 1.0)
        length_penalty_threshold: Minimum acceptable hint length
        max_hint_length: Maximum hint length before truncation
        solution_copy_penalty: Penalty if hint copies too much of solution
        empty_hint_penalty: Penalty for empty/trivial hints
        log_every_n: Print debug information every N samples

    Returns:
        float: The computed reward score
    """
    global _log_counter
    _log_counter += 1
    verbose = (_log_counter % log_every_n == 1)  # Log first sample and every N-th after

    # Load student model (cached after first call)
    student_model, student_tokenizer = _load_student_model(
        model_name=student_model_name,
        device=student_device
    )

    # Extract hint from teacher's response
    hint = extract_hint_from_response(solution_str)

    # Get question and solution from ground_truth or extra_info
    if isinstance(ground_truth, dict):
        question = ground_truth.get("question", "")
        solution = ground_truth.get("solution", "")
    elif extra_info is not None:
        question = extra_info.get("question", "")
        solution = extra_info.get("solution", "")
    else:
        print("Warning: No question/solution found in ground_truth or extra_info")
        return empty_hint_penalty

    # Debug: Print teacher's generated hint
    if verbose:
        _print_separator(f"RLT REWARD COMPUTATION (Sample #{_log_counter})")
        print(f"[DATA SOURCE]: {data_source}")
        print(f"\n[QUESTION]:\n{_truncate_for_display(question, 500)}")
        print(f"\n[GROUND TRUTH SOLUTION]:\n{_truncate_for_display(solution, 500)}")
        print(f"\n[TEACHER RAW OUTPUT]:\n{_truncate_for_display(solution_str, 500)}")
        print(f"\n[EXTRACTED HINT]:\n{_truncate_for_display(hint, 500)}")

    # Sanity checks
    # 1. Empty or too short hint
    if len(hint.strip()) < length_penalty_threshold:
        if verbose:
            print(f"\n[PENALTY]: Hint too short ({len(hint.strip())} chars < {length_penalty_threshold})")
            print(f"[REWARD]: {empty_hint_penalty}")
        return empty_hint_penalty

    # 2. Truncate overly long hints
    if len(hint) > max_hint_length:
        if verbose:
            print(f"\n[INFO]: Truncating hint from {len(hint)} to {max_hint_length} chars")
        hint = hint[:max_hint_length]

    # 3. Check if hint copies solution directly (similarity check)
    # Simple check: if hint contains more than 50% of solution tokens
    hint_tokens = set(hint.lower().split())
    solution_tokens = set(solution.lower().split())
    if len(solution_tokens) > 0:
        overlap = len(hint_tokens & solution_tokens) / len(solution_tokens)
        if overlap > 0.5:
            if verbose:
                print(f"\n[PENALTY]: Hint copies solution (overlap={overlap:.2%})")
                print(f"[REWARD]: {solution_copy_penalty}")
            return solution_copy_penalty

    # Compute the RLT reward with perplexity-based KL proxy
    try:
        # Component 1: r_SS - Solution understanding reward
        logprob_stats = compute_solution_logprob(
            question=question,
            hint=hint,
            solution=solution,
            student_model=student_model,
            student_tokenizer=student_tokenizer,
            verbose=verbose
        )

        # r_SS = mean + alpha * min
        r_SS = (logprob_stats["mean_logprob"] + 
                alpha * logprob_stats["min_logprob"])

        # Component 2: r_KL_proxy - Student perplexity as KL proxy
        if use_kl_proxy:
            perplexity_stats = compute_student_perplexity(
                question=question,
                hint=hint,
                student_model=student_model,
                student_tokenizer=student_tokenizer,
                verbose=verbose
            )
            
            # Convert perplexity to penalty
            # Use log(perplexity) to keep scale similar to log probs
            # Also include min term like in r_SS for consistency
            log_perplexity = np.log(perplexity_stats["perplexity"])
            
            # r_KL_proxy = log(perplexity) + alpha * min(log_prob)
            # Higher perplexity -> higher penalty
            # Lower min_logprob -> higher penalty
            r_KL_proxy = (log_perplexity * perplexity_scale + 
                          alpha * (-perplexity_stats["min_logprob"]))  # Negative because lower is worse
        else:
            if verbose:
                print("\n[INFO]: KL proxy disabled, r_KL_proxy = 0")
            r_KL_proxy = 0.0
            perplexity_stats = None

        # Final RLT reward: r_RLT = r_SS - lambda * r_KL_proxy
        reward = r_SS - lambda_kl * r_KL_proxy

        if verbose:
            _print_separator("REWARD CALCULATION")
            print(f"[Solution Understanding (r_SS)]:")
            print(f"  - mean_logprob: {logprob_stats['mean_logprob']:.4f}")
            print(f"  - min_logprob:  {logprob_stats['min_logprob']:.4f}")
            print(f"  - alpha:        {alpha}")
            print(f"  - r_SS = mean + alpha * min")
            print(f"  - r_SS = {logprob_stats['mean_logprob']:.4f} + {alpha} * {logprob_stats['min_logprob']:.4f}")
            print(f"  - r_SS = {r_SS:.4f}")
            
            if use_kl_proxy and perplexity_stats is not None:
                print(f"\n[KL Proxy (Student Perplexity)]:")
                print(f"  - perplexity:       {perplexity_stats['perplexity']:.4f}")
                print(f"  - log(perplexity):  {log_perplexity:.4f}")
                print(f"  - min_logprob:      {perplexity_stats['min_logprob']:.4f}")
                print(f"  - alpha:            {alpha}")
                print(f"  - perplexity_scale: {perplexity_scale}")
                print(f"  - r_KL_proxy = log(perplexity) * scale + alpha * (-min_logprob)")
                print(f"  - r_KL_proxy = {log_perplexity:.4f} * {perplexity_scale} + {alpha} * {-perplexity_stats['min_logprob']:.4f}")
                print(f"  - r_KL_proxy = {r_KL_proxy:.4f}")
            else:
                print(f"\n[KL Proxy]: DISABLED (r_KL_proxy = 0)")
            
            print(f"\n[Final Reward Calculation]:")
            print(f"  - Formula: r_RLT = r_SS - lambda_kl * r_KL_proxy")
            print(f"  - r_RLT = {r_SS:.4f} - {lambda_kl} * {r_KL_proxy:.4f}")
            print(f"  - r_RLT = {reward:.4f}")
            print("=" * 80 + "\n")

    except Exception as e:
        print(f"Error computing reward: {e}")
        import traceback
        traceback.print_exc()
        reward = empty_hint_penalty

    return reward


def compute_score_batch(
    data_sources: list[str],
    solution_strs: list[str],
    ground_truths: list[Any],
    extra_infos: Optional[list[dict]] = None,
    **kwargs
) -> list[float]:
    """
    Batch version of compute_score for efficiency.

    Note: Currently calls compute_score in a loop, but can be optimized
    for batch processing with the student model in the future.
    
    Args:
        data_sources: List of data source identifiers
        solution_strs: List of teacher-generated responses
        ground_truths: List of ground truth dicts
        extra_infos: List of extra info dicts
        **kwargs: Additional arguments passed to compute_score
    
    Returns:
        List of reward scores
    """
    if extra_infos is None:
        extra_infos = [None] * len(solution_strs)

    rewards = []
    for ds, sol, gt, ei in zip(data_sources, solution_strs, ground_truths, extra_infos):
        reward = compute_score(ds, sol, gt, ei, **kwargs)
        rewards.append(reward)

    return rewards